### ISSUE TITLE
Why did you remove the clean shutdown code from net.cpp?

### ISSUE THREAD

**Issue by Crypto2** [onsightit/solarcoin#20]
This is needed on Linux so SIGINT/SIGTERM will shut down solarcoind cleanly so databases and wallets don't get corrupted.

To re-add go to the end of ThreadMessageHandler2 and add this right below MilliSleep(100):
        if (fRequestShutdown)
            StartShutdown();

**Comment by onsightit** [comment]
Thanks, Crypto2!
