### ISSUE TITLE
Minimizing system requirements for future applications (include features like pruning)

### ISSUE THREAD

**Issue by Dommsko** [onsightit/solarcoin#25]
I tried to run solarcoind on a Raspberry Pi Zero which only has 512 MB of RAM. While this would be enough to run bitcoind, solarcoind seems to have a much higher demand for resources. My plan is to develop a cheap Pi Zero-based embedded system for solar panel owners that should pay off as fast as possible by the generated staking interest, hopefully allowing the network to snowball.

First research provided evidence that it might have to do with the block index. I suppose that RAM demand for the index increases when the chain length, possibly disqualifying even more powerful devices like the Pi 3 (1GB RAM) in the near future.

I found out that bitcoind supports blockchain pruning since v0.11, and pruning while preserving wallet functionality since v0.12. Is it possible to include similar performance-related methods in the solarcoind client?

**Comment by onsightit** [comment]
This is currently in progress as we are upgrading the legacy SolarCoin code to bitcoin core 0.15.1.0.
